#!/usr/bin/env python3
"""100_kjv_word_index_on_neither_list.py — list the KJV Bible Word Index
entries (references/eya-new-words-list/, script 97) whose words are on
NEITHER references/word_blacklist.md NOR references/word_whitelist.md
(owner request 2026-10-04).

Entry expansion, blacklist headwords and whitelist sections are imported
from scripts 98 and 99, so all three lists split and match identically.

Output: references/eya-new-words-list/on_neither_list.md with
  1. entries with NO form on either list, and
  2. entries with SOME forms on neither list (the rest on a list, named).
Read-only on every input; overwrite guard refuses a version with fewer
entries than the existing file.
"""
import csv
import importlib
import re
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "references" / "eya-new-words-list" / "kjv_word_index.tsv"
OUT = ROOT / "references" / "eya-new-words-list" / "on_neither_list.md"

sys.path.insert(0, str(ROOT / "scripts"))
s98 = importlib.import_module("98_kjv_word_index_not_blacklisted")
s99 = importlib.import_module("99_kjv_word_index_on_whitelist")


def main():
    black = s98.blacklist_headwords()
    reviewed, names = s99.whitelist_sections()
    white = reviewed | names
    entries = OrderedDict()  # entry -> [times, verse count]
    with TSV.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            e = entries.setdefault(row["word"], [row["times_in_kjv"], 0])
            e[1] += 1

    def where(w):
        lw = w.lower()
        return [n for n, s in (("blacklist", black), ("whitelist", white)) if lw in s]

    clear, partial = [], []
    for entry, (times, verses) in entries.items():
        forms = s98.expand(entry)
        free = [w for w in forms if not where(w)]
        listed = [f"{w} ({' + '.join(where(w))})" for w in forms if where(w)]
        if not listed:
            clear.append((entry, times, verses))
        elif free:
            partial.append((entry, times, ", ".join(free), ", ".join(listed)))

    md = [
        "# KJV Word Index — words on neither list",
        "",
        "Generated by `scripts/100_kjv_word_index_on_neither_list.py` from "
        "`kjv_word_index.tsv`, `references/word_blacklist.md` "
        f"({len(black)} headwords) and `references/word_whitelist.md` "
        f"({len(reviewed)} reviewed words, {len(names)} proper names). Each "
        "index entry is expanded into its forms the same way as "
        "`not_on_blacklist.md` and `on_whitelist.md` (`Alien/s` → alien, "
        "aliens; parenthetical notes dropped) and every form is matched "
        "case-insensitively against both lists.",
        "",
        f"**{len(entries)} index entries: {len(clear)} with no form on either "
        f"list, {len(partial)} with only some forms on neither, "
        f"{len(entries) - len(clear) - len(partial)} with every form on a list.**",
        "",
        f"## 1. No form on either list ({len(clear)})",
        "",
        "| Index entry | Times in KJV (site) | Example verses |",
        "|---|---|---|",
    ]
    md += [f"| {e} | {t} | {v} |" for e, t, v in clear]
    md += [
        "",
        f"## 2. Some forms on neither list ({len(partial)})",
        "",
        "| Index entry | Times in KJV (site) | On neither list | On a list |",
        "|---|---|---|---|",
    ]
    md += [f"| {e} | {t} | {f} | {l} |" for e, t, f, l in partial]
    text = "\n".join(md) + "\n"

    if OUT.exists():
        old = OUT.read_text(encoding="utf-8")
        if old == text:
            print(f"{OUT.relative_to(ROOT)}: already current")
            return
        old_rows = len(re.findall(r"^\| (?!Index entry|---)", old, re.M))
        if len(clear) + len(partial) < old_rows:
            print(f"REFUSED: {OUT.relative_to(ROOT)} has {old_rows} rows; "
                  f"new version has {len(clear) + len(partial)}.")
            return
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(clear)} clear, {len(partial)} partial, "
          f"{len(entries) - len(clear) - len(partial)} fully listed")


if __name__ == "__main__":
    main()
