#!/usr/bin/env python3
"""103_parentheses_1611_vs_1769.py — list every verse that has parentheses in
the 1611 King James text (`KJV1611`, script 102) or the 1769 Standard Oxford
Edition (`KJV`, the base text), with both readings side by side
(owner request 2026-10-04).

A verse counts if its text contains "(" or ")". Parenthetical passages can
run across a verse boundary, so a verse may hold only one of the pair; those
are flagged "spans verses". Square brackets are not counted (the 1611
transcription uses them only for psalm titles).

Output: references/verses/parenthesis_1611_vs_1769.md, in three sections —
in both editions, in 1611 only, in 1769 only — each in canonical book order.
Read-only on db/mandela.db; overwrite guard refuses a version listing fewer
verses than the existing file. Advisory comparison only (Premise Revision).
"""
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "db" / "mandela.db"
OUT = ROOT / "references" / "verses" / "parenthesis_1611_vs_1769.md"


def has_paren(s):
    return "(" in s or ")" in s


def balanced(s):
    return s.count("(") == s.count(")")


def main():
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    names = dict(con.execute("SELECT id, name FROM books WHERE translation='KJV'"))

    def texts(code):
        return {(b, c, v): t for b, c, v, t in con.execute(
            "SELECT book_id, chapter, verse, text FROM verses WHERE translation=?",
            (code,))}

    old, std = texts("KJV1611"), texts("KJV")
    con.close()
    p_old = {k for k in old if has_paren(old[k])}
    p_std = {k for k in std if has_paren(std[k])}
    groups = [
        ("In both editions", sorted(p_old & p_std)),
        ("In the 1611 text only", sorted(p_old - p_std)),
        ("In the 1769 Standard Oxford Edition only", sorted(p_std - p_old)),
    ]
    total = len(p_old | p_std)

    def entry(k):
        b, c, v = k
        a, o = old.get(k, "(verse missing)"), std.get(k, "(verse missing)")
        flags = [f"{ed} spans verses" for ed, t, p in
                 (("1611", a, p_old), ("1769", o, p_std))
                 if k in p and not balanced(t)]
        head = f"### {names[b]} {c}:{v}" + (f" — *{'; '.join(flags)}*" if flags else "")
        return [head, "", f"- **1611:** {a}", f"- **1769:** {o}", ""]

    md = [
        "# Parentheses — 1611 King James vs 1769 Standard Oxford Edition",
        "",
        "Generated by `scripts/103_parentheses_1611_vs_1769.py` from "
        "`db/mandela.db`: `KJV1611` (the 1611 original-spelling transcription, "
        "script 102) and `KJV` (the 1769 Blayney text, the project's base). "
        "Every verse with a \"(\" or \")\" in either edition, both readings in "
        "full. Neither text includes this project's restorations.",
        "",
        f"**{total} verses: {len(groups[0][1])} in both editions, "
        f"{len(groups[1][1])} in 1611 only, {len(groups[2][1])} in 1769 only.** "
        "A verse marked *spans verses* holds only one half of a parenthesis "
        "that opens or closes in a neighbouring verse.",
        "",
        "Advisory comparison only — under the Premise Revision both editions "
        "are written texts and neither outranks memory testimony. The 1611 "
        "text is a transcription: confirm any reading you rely on against the "
        "page facsimile.",
        "",
    ]
    for i, (title, keys) in enumerate(groups, 1):
        md += [f"## {i}. {title} ({len(keys)})", ""]
        for k in keys:
            md += entry(k)
    text = "\n".join(md)

    if OUT.exists():
        prev = OUT.read_text(encoding="utf-8")
        if prev == text:
            print(f"{OUT.relative_to(ROOT)}: already current")
            return
        prev_n = len(re.findall(r"^### ", prev, re.M))
        if total < prev_n:
            print(f"REFUSED: {OUT.relative_to(ROOT)} lists {prev_n} verses; "
                  f"new version lists {total}.")
            return
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {total} verses — "
          + ", ".join(f"{len(k)} {t.lower()}" for t, k in groups))


if __name__ == "__main__":
    main()
