#!/usr/bin/env python3
"""16_apply_word_review.py — Phase 3: ingest the king-james agent word review.

Reads references/word_reviews/batch_*.tsv (produced by the
king-james-middle-english-expert agent, owner directive 2026-07-14: review
all uncleared non-proper-noun words for period accuracy AND possible
letter-level typos; advise alternates on strong belief).

TSV format: word<TAB>verdict<TAB>alternate<TAB>note
  verdict: period | suspect | typo

Updates `word_era`: verdict (typo stored as 'typo'), first_use_source
'KJ-agent 2026-07-14', plus alternate_word / review_note columns (added
here if missing). Only rows still carrying verdict 'suspect' are touched —
the corpus-attested and proper-noun verdicts from script 05 stand.

Emits references/word_review_report.md: every word the agent holds a strong
belief against, with its advised alternate.

Idempotent: re-applies the TSVs and regenerates the report each run.
"""

import sqlite3
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "db" / "mandela.db"
REVIEW_DIR = REPO_ROOT / "references" / "word_reviews"
REPORT = REPO_ROOT / "references" / "word_review_report.md"
SOURCE = "KJ-agent 2026-07-14"
VALID = {"period", "suspect", "typo"}


def main() -> None:
    con = sqlite3.connect(DB_PATH)
    try:
        cols = {r[1] for r in con.execute("PRAGMA table_info(word_era)")}
        if "alternate_word" not in cols:
            con.execute("ALTER TABLE word_era ADD COLUMN alternate_word TEXT")
        if "review_note" not in cols:
            con.execute("ALTER TABLE word_era ADD COLUMN review_note TEXT")

        # batches first, then the second-opinion pass (verse-verified, high bar)
        # so its verdicts override the first pass
        files = sorted(REVIEW_DIR.glob("batch_*.tsv"))
        second = REVIEW_DIR / "second_opinion.tsv"
        if second.exists():
            files.append(second)
        rows, bad = [], []
        for tsv in files:
            for ln in tsv.read_text(encoding="utf-8").splitlines():
                if not ln.strip():
                    continue
                parts = ln.split("\t")
                if len(parts) < 2 or parts[1].strip().lower() not in VALID:
                    bad.append(f"{tsv.name}: {ln[:60]}")
                    continue
                parts += [""] * (4 - len(parts))
                word, verdict, alt, note = (p.strip() for p in parts[:4])
                rows.append((word.lower(), verdict.lower(), alt or None, note or None))

        counts = {"period": 0, "suspect": 0, "typo": 0, "unmatched": 0}
        for word, verdict, alt, note in rows:
            cur = con.execute(
                """UPDATE word_era SET verdict=?, first_use_source=?,
                   alternate_word=?, review_note=?
                   WHERE word=? AND (first_use_source IS NULL OR first_use_source=?)""",
                (verdict, SOURCE, alt, note, word, SOURCE))
            if cur.rowcount:
                counts[verdict] += 1
            else:
                counts["unmatched"] += 1
        con.commit()

        # report from FINAL state (second-opinion overrides included)
        flagged = [(w, v, a or "", n or "", c or 0) for w, v, a, n, c in con.execute(
            """SELECT we.word, we.verdict, we.alternate_word, we.review_note, wc.count
               FROM word_era we
               LEFT JOIN word_counts wc ON wc.word=we.word AND wc.book_id IS NULL
                 AND wc.tokenizer_version=2
               WHERE we.first_use_source=? AND we.verdict IN ('suspect','typo')""",
            (SOURCE,))]

        flagged.sort(key=lambda x: (-x[4], x[0]))
        lines = ["# Word Review Report — king-james agent, 2026-07-14",
                 "",
                 "*Generated by `scripts/16_apply_word_review.py` — do not hand-edit.*",
                 "",
                 "Two-pass review: 8 parallel first-pass batches over the 2,060 "
                 "uncleared words, then a verse-verified second-opinion pass over "
                 "everything the first pass flagged (65 words) — the second pass "
                 "overrides the first.",
                 "",
                 "Words held with STRONG BELIEF against, with advised period alternates",
                 "(advisory evidence per Decision Log #5 — memory still leads):",
                 "",
                 "| word | KJV count | verdict | advised alternate | note |",
                 "|------|-----------|---------|-------------------|------|"]
        lines += [f"| {w} | {c} | {v} | {a} | {n} |" for w, v, a, n, c in flagged]
        REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

        print(f"applied: {counts}")
        if bad:
            print(f"skipped {len(bad)} malformed line(s), e.g. {bad[:3]}")
        print(f"{len(flagged)} words with strong-belief alternates -> {REPORT}")
    finally:
        con.close()


if __name__ == "__main__":
    main()
