#!/usr/bin/env python3
"""18_rare_word_alternatives.py — Phase 3/6: alternatives for remaining rare words.

Owner directive 2026-07-15: take all remaining words with only 1–2 uses and
list alternatives in a file for review, including alternative words used in
other bibles.

Scope: every KJV word with <= 2 occurrences bible-wide that is not a proper
noun and not already flagged suspect/typo ("remaining" = verdict 'period').

For each word the report lists:
  - its verse reference(s) and the verse text;
  - KJV parallel renderings: how the KJV renders the same underlying
    Hebrew/Greek word (same Strong's number, per-testament) elsewhere —
    the project's approved use of the KJV (find similar words, never
    authenticity evidence);
  - witness alternatives: words the other bibles use at the same verse that
    the KJV does not (from verse_diffs), per witness.

Output: references/rare_word_alternatives.md (generated — do not hand-edit).
"""

import re
import sqlite3
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "db" / "mandela.db"
OUT = REPO_ROOT / "references" / "rare_word_alternatives.md"
TOKEN_RE = re.compile(r"[A-Za-z]+(?:['’–-][A-Za-z]+)*")
WITNESSES = ["Geneva1599", "Tyndale", "Wycliffe", "Webster", "YLT", "DRC"]

# alignment noise: function words that show up in loose word-level linkages
STOP = set("""a an and the that this those these i thou he she it we ye you
they me him her us them my thy his its our your their of to in on for with
by at from unto into upon as is are was were be been am art shall will not
no nor but or so if then than there here when why how which who whom whose
what do doth did done have hath had haue also out up down over all any some
more most them's let may can could would should o oh yea verily""".split())


def fold(form: str) -> str:
    return form.lower().replace("’", "'").replace("–", "-")


def main() -> None:
    con = sqlite3.connect(DB_PATH)

    rare = [w for (w,) in con.execute(
        """SELECT wc.word FROM word_counts wc JOIN word_era we ON we.word = wc.word
           WHERE wc.translation='KJV' AND wc.book_id IS NULL
             AND wc.tokenizer_version=2 AND wc.count <= 2
             AND we.verdict = 'period' ORDER BY wc.word""")]
    rare_set = set(rare)
    print(f"{len(rare)} remaining rare words (<=2 uses, period, non-proper)")

    # word -> [(book_id, book, chapter, verse, verse_id, text)]
    verses_of = defaultdict(list)
    books = dict(con.execute("SELECT id, name FROM books WHERE translation='KJV'"))
    for vid, bid, ch, vs, text in con.execute(
            "SELECT id, book_id, chapter, verse, text FROM verses "
            "WHERE translation='KJV'"):
        toks = {fold(t) for t in TOKEN_RE.findall(text)}
        for w in toks & rare_set:
            verses_of[w].append((bid, books[bid], ch, vs, vid, text))

    # (testament, strongs) mapping from BibleForge word-level data
    print("building Strong's maps (one-time pass)...")
    word_strongs = defaultdict(set)     # folded english word -> {(lang, strongs)}
    strongs_words = defaultdict(Counter)  # (lang, strongs) -> Counter(english word)
    for book, eword, strongs in con.execute(
            """SELECT e.book, e.word, o.strongs FROM bf_words_en e
               JOIN bf_words_orig o ON o.id = e.orig_id
               WHERE e.word != '' AND o.strongs > 0"""):
        lang = "H" if book <= 39 else "G"
        for tok in TOKEN_RE.findall(eword):
            f = fold(tok)
            word_strongs[f].add((lang, strongs))
            strongs_words[(lang, strongs)][f] += 1

    # witness-only words per (verse_id, witness) from verse_diffs
    diffs = {}
    ph = ",".join("?" * len(WITNESSES))
    for vid, wit, notable in con.execute(
            f"SELECT verse_id, witness, notable FROM verse_diffs "
            f"WHERE witness IN ({ph}) AND notable != ''", WITNESSES):
        m = re.search(rf"{wit}-only: (.*)$", notable or "")
        if m and m.group(1).strip():
            diffs[(vid, wit)] = m.group(1).strip()

    lines = ["# Rare Word Alternatives — review file",
             "",
             "*Generated by `scripts/18_rare_word_alternatives.py` — do not hand-edit.*",
             "",
             f"All {len(rare)} remaining KJV words with 1–2 uses bible-wide "
             "(non-proper-noun, currently verdict `period`). For each: the KJV's "
             "own renderings of the same Hebrew/Greek word elsewhere (allowed use "
             "of the KJV — similar-word lookup, not authenticity evidence), and "
             "the words other bibles use at the same verses that the KJV does not.",
             ""]

    for w in rare:
        occs = verses_of.get(w, [])
        count = sum(1 for o in occs)
        lines.append(f"## {w} ({len(occs)} verse{'s' if len(occs)!=1 else ''})")
        lines.append("")

        # KJV parallel renderings via Strong's
        alts = Counter()
        for key in word_strongs.get(w, ()):
            for other, c in strongs_words[key].items():
                if other != w and other not in STOP:
                    alts[other] += c
        if alts:
            top = ", ".join(f"{a} ({c})" for a, c in alts.most_common(8))
            lines.append(f"- **KJV renders the same original word elsewhere as:** {top}")
        else:
            lines.append("- **KJV parallel renderings:** none found (no Strong's "
                         "linkage or unique rendering)")

        for bid, book, ch, vs, vid, text in occs:
            lines.append(f"- **{book} {ch}:{vs}** — {text}")
            for wit in WITNESSES:
                d = diffs.get((vid, wit))
                if d:
                    lines.append(f"  - {wit} uses: {d}")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"-> {OUT} ({len(lines)} lines)")
    con.close()


if __name__ == "__main__":
    main()
