#!/usr/bin/env python3
"""25_uncleared_inflection_triage.py — move inflection-only words out of
references/uncleared_words.md (owner directive 2026-07-17).

A word on the uncleared list (attested in no pre-1611 corpus) whose base word
IS cleared and common in the KJV is uncleared only by inflection — plural,
possessive, tense, past tense, progressive, past participle, comparative,
superlative — not a genuinely undated vocabulary item. Those rows move to
references/uncleared_words_inflection_only.md, annotated "Inflection
Deviation" with the base word and its KJV count. Derivational forms (-ness,
-ly, -tion, ...) do not qualify. Ambiguous -er/-en forms (agent noun /
verbification vs. comparative / past participle) are listed for owner review,
not moved.

Idempotent: moved rows are gone from the source on re-run.
"""
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
importable = __import__("importlib").import_module
mod = importable("24_extract_inflection_only")
base_candidates = mod.base_candidates

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "references" / "uncleared_words.md"
OUT = ROOT / "references" / "removed_words" / "uncleared_words_inflection_only.md"
DB_PATH = ROOT / "db" / "mandela.db"
COMMON_THRESHOLD = 2
AMBIGUOUS = ("comparative", "past participle")

ROW_RE = re.compile(r"^\| (\S+) \| (\d+) \|$")


def main():
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    (latest,) = con.execute(
        "SELECT MAX(tokenizer_version) FROM word_counts").fetchone()
    counts = dict(con.execute(
        "SELECT word, count FROM word_counts WHERE translation='KJV' "
        "AND book_id IS NULL AND tokenizer_version=?", (latest,)))
    con.close()

    lines = SRC.read_text(encoding="utf-8").splitlines()
    uncleared = {m.group(1) for l in lines if (m := ROW_RE.match(l))}

    kept, moved, ambiguous = [], [], []
    for line in lines:
        m = ROW_RE.match(line)
        if not m:
            kept.append(line)
            continue
        word, wc = m.group(1), int(m.group(2))
        hit = None
        for base, kind in base_candidates(word):
            if base not in uncleared and counts.get(base, 0) > COMMON_THRESHOLD:
                hit = (base, kind, counts[base])
                break
        if hit and hit[1].startswith(AMBIGUOUS):
            kept.append(line)
            ambiguous.append((word, wc) + hit)
        elif hit:
            moved.append((word, wc) + hit)
        else:
            kept.append(line)

    # Preservation guard (owner directive 2026-07-17): never overwrite an
    # existing output with an emptier one — generated review files must not
    # be lost on an idempotent re-run.
    if not moved and OUT.exists():
        print("nothing to move; existing output file left untouched")
        return

    out = ["# Uncleared words removed: Inflection Deviation", "",
           "*Generated by `scripts/25_uncleared_inflection_triage.py` (owner "
           "directive 2026-07-17).* Each word below was uncleared only "
           "because its inflected form is unattested pre-1611 — its base "
           "word is cleared and common in the KJV, so era dating applies to "
           "the base, not the inflection. Removed from "
           "`uncleared_words.md`; no manual dating needed.", "",
           "| word | KJV count | reason | base word | base KJV count |",
           "|------|-----------|--------|-----------|----------------|"]
    for word, wc, base, kind, bc in moved:
        out.append(f"| {word} | {wc} | Inflection Deviation ({kind}) "
                   f"| {base} | {bc} |")
    if ambiguous:
        out += ["", "## Ambiguous -er/-en forms (NOT moved — could be "
                "derivation, owner ruling needed)", "",
                "*-er may be comparative (inflection) or agent noun "
                "(derivation); -en may be past participle (inflection) or "
                "adjective→verb (derivation).*", "",
                "| word | KJV count | reading | base word | base KJV count |",
                "|------|-----------|---------|-----------|----------------|"]
        for word, wc, base, kind, bc in ambiguous:
            out.append(f"| {word} | {wc} | {kind} | {base} | {bc} |")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    SRC.write_text("\n".join(kept) + "\n", encoding="utf-8")
    print(f"moved {len(moved)} words; {len(ambiguous)} ambiguous flagged; "
          f"{len(uncleared) - len(moved)} words remain uncleared")


if __name__ == "__main__":
    main()
