#!/usr/bin/env python3
"""26_prune_inflection_from_batches.py — move Inflection Deviation entries out
of the witness batch files (owner directive 2026-07-17).

Entries moved to references/removed_words/rare_word_inflection_only.md need no
replacement, so their witness-batch entries are dead weight for the agent
pass. This script removes them from
references/rare_word_witness_batches/batch_NNNN.md and appends them (with
batch provenance) to
references/removed_words/batch_entries_inflection_only.md — moved, never
deleted, per the preservation rule.

Batches currently being processed can be excluded with --skip (e.g.
--skip 54-56 72-86) and pruned on a later run. Idempotent: already-pruned
entries are simply absent; the archive file is appended to, never rewritten,
and duplicate archive appends are prevented by checking existing headers.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INFLECTION = ROOT / "references" / "removed_words" / "rare_word_inflection_only.md"
BATCH_DIR = ROOT / "references" / "rare_word_witness_batches"
ARCHIVE = ROOT / "references" / "removed_words" / "batch_entries_inflection_only.md"


def parse_ranges(specs):
    nums = set()
    for spec in specs or []:
        if "-" in spec:
            a, b = spec.split("-")
            nums.update(range(int(a), int(b) + 1))
        else:
            nums.add(int(spec))
    return nums


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip", nargs="*", default=[],
                    help="batch numbers/ranges to leave untouched, e.g. 54-56 72-86")
    args = ap.parse_args()
    skip = parse_ranges(args.skip)

    moved_headers = {l for l in INFLECTION.read_text(encoding="utf-8").splitlines()
                     if l.startswith("## ")}
    # drop section headers of the review file itself
    moved_headers = {h for h in moved_headers if " → " in h}

    if ARCHIVE.exists():
        archived = {l for l in ARCHIVE.read_text(encoding="utf-8").splitlines()
                    if l.startswith("## ")}
    else:
        ARCHIVE.write_text(
            "# Witness-batch entries moved out: Inflection Deviation\n\n"
            "*Generated by `scripts/26_prune_inflection_from_batches.py`.* "
            "Entries pruned from the batch files because their words were "
            "triaged as Inflection Deviation (see "
            "`rare_word_inflection_only.md`). Preserved here with batch "
            "provenance; never deleted.\n\n", encoding="utf-8")
        archived = set()

    total_removed = 0
    archive_add = []
    for bf in sorted(BATCH_DIR.glob("batch_[0-9]*.md")):
        m = re.match(r"batch_(\d+)\.md$", bf.name)
        if not m or int(m.group(1)) in skip or "_proposals" in bf.name:
            continue
        lines = bf.read_text(encoding="utf-8").splitlines()
        # split into preamble + entries (entry = header line through next header)
        kept, removed_here = [], 0
        block, block_moved = [], False
        def flush():
            nonlocal removed_here
            if not block:
                return
            if block_moved:
                removed_here += 1
                if block[0] not in archived:
                    archived.add(block[0])
                    archive_add.append(block[0])
                    archive_add.append(f"*(from {bf.name})*")
                    archive_add.extend(block[1:])
            else:
                kept.extend(block)
        for line in lines:
            if line.startswith("## "):
                flush()
                block, block_moved = [line], line in moved_headers
            elif block:
                block.append(line)
            else:
                kept.append(line)
        flush()
        if removed_here:
            bf.write_text("\n".join(kept) + "\n", encoding="utf-8")
            total_removed += removed_here
            print(f"{bf.name}: removed {removed_here}")
    if archive_add:
        with ARCHIVE.open("a", encoding="utf-8") as f:
            f.write("\n".join(archive_add) + "\n")
    print(f"total entries pruned: {total_removed}; skipped batches: "
          f"{sorted(skip) if skip else 'none'}")


if __name__ == "__main__":
    main()
