#!/usr/bin/env python3
"""27_prune_inflection_from_proposals.py — move Inflection Deviation entries
out of the batch *proposal* files (owner directive 2026-07-17).

Companion to script 26 (which prunes the batch source files). Proposal entries
for words triaged as Inflection Deviation are moot — those verses keep their
original KJV wording — so they are moved (never deleted) from
references/rare_word_witness_batches/batch_NNNN_proposals.md to
references/removed_words/proposal_entries_inflection_only.md with provenance.

Proposal headers are "## rareword → proposed — Book C:V" where *proposed*
differs from the original selection, so matching uses (rareword, verse ref),
not the whole header. Batches still being written can be excluded with
--skip. Idempotent; the archive is append-only with duplicate protection.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INFLECTION = ROOT / "references" / "removed_words" / "rare_word_inflection_only.md"
BATCH_DIR = ROOT / "references" / "rare_word_witness_batches"
ARCHIVE = ROOT / "references" / "removed_words" / "proposal_entries_inflection_only.md"

HEADER_RE = re.compile(r"^## (.+?) → .*? — (.+)$")


def key_of(header):
    m = HEADER_RE.match(header)
    return (m.group(1).strip().lower(), m.group(2).strip()) if m else None


def parse_ranges(specs):
    nums = set()
    for spec in specs or []:
        if "-" in spec:
            a, b = spec.split("-")
            nums.update(range(int(a), int(b) + 1))
        else:
            nums.add(int(spec))
    return nums


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip", nargs="*", default=[],
                    help="batch numbers/ranges to leave untouched")
    args = ap.parse_args()
    skip = parse_ranges(args.skip)

    moved_keys = {key_of(l) for l in
                  INFLECTION.read_text(encoding="utf-8").splitlines()
                  if l.startswith("## ") and " → " in l}
    moved_keys.discard(None)

    if ARCHIVE.exists():
        archived = {key_of(l) for l in
                    ARCHIVE.read_text(encoding="utf-8").splitlines()
                    if l.startswith("## ")}
    else:
        ARCHIVE.write_text(
            "# Proposal entries moved out: Inflection Deviation\n\n"
            "*Generated by `scripts/27_prune_inflection_from_proposals.py`.* "
            "Agent proposals for words later triaged as Inflection Deviation "
            "(see `rare_word_inflection_only.md`) — the verses keep their "
            "original KJV wording, so these proposals are moot but preserved "
            "here with provenance; never deleted.\n\n", encoding="utf-8")
        archived = set()

    total = 0
    archive_add = []
    for pf in sorted(BATCH_DIR.glob("batch_*_proposals.md")):
        n = int(re.match(r"batch_(\d+)_proposals\.md$", pf.name).group(1))
        if n in skip:
            continue
        lines = pf.read_text(encoding="utf-8").splitlines()
        kept, block, block_moved, removed_here = [], [], False, 0

        def flush():
            nonlocal removed_here
            if not block:
                return
            if block_moved:
                removed_here += 1
                k = key_of(block[0])
                if k not in archived:
                    archived.add(k)
                    archive_add.append(block[0])
                    archive_add.append(f"*(from {pf.name})*")
                    archive_add.extend(block[1:])
            else:
                kept.extend(block)

        for line in lines:
            if line.startswith("## "):
                flush()
                block, block_moved = [line], key_of(line) in moved_keys
            elif block:
                block.append(line)
            else:
                kept.append(line)
        flush()
        if removed_here:
            pf.write_text("\n".join(kept) + "\n", encoding="utf-8")
            total += removed_here
            print(f"{pf.name}: removed {removed_here}")
    if archive_add:
        with ARCHIVE.open("a", encoding="utf-8") as f:
            f.write("\n".join(archive_add) + "\n")
    print(f"total proposal entries pruned: {total}; skipped: "
          f"{sorted(skip) if skip else 'none'}")


if __name__ == "__main__":
    main()
