#!/usr/bin/env python3
"""28_split_proposals_for_review.py — split all batch proposals into two
owner-review files (owner directive 2026-07-17).

1. references/rare_word_review_no_safe_swap.md — every NO-SAFE-SWAP entry
   (needs owner ruling; owner accepts ~90-95% as factual, i.e. the flagged
   word stays because no alternative exists).
2. references/rare_word_ai_suggestions.md — every KEEP/REVISE entry: the
   AI-suggested change with rationale and NEW text.

Owner-ruled exceptions (2026-07-17) are annotated inline where found:
  - grandmother (II Timothy 1:5) → "mother's mother" (era kinship words are
    only husband/wife/brother/sister/father/mother)
  - horseleach (Proverbs 30:15) → probably "leach"
  - ladder (Genesis 28:12) → DO NOT CHANGE (Jacob's ladder stays)

Reads every batch_NNNN_proposals.md; refuses to run if any batch_NNNN.md
lacks a proposals file (the split is meant for the completed set) unless
--partial is given. Output files are regenerated wholesale on each run (they
are derived views; the proposal files remain the preserved source of truth).
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BATCH_DIR = ROOT / "references" / "rare_word_witness_batches"
OUT_NSS = ROOT / "references" / "rare_word_review_no_safe_swap.md"
OUT_AI = ROOT / "references" / "rare_word_ai_suggestions.md"

OWNER_RULINGS = {
    ("grandmother", "II Timothy 1:5"):
        "OWNER RULING 2026-07-17: use \"mother's mother\" — era kinship "
        "words are only husband/wife/brother/sister/father/mother.",
    ("horseleach", "Proverbs 30:15"):
        "OWNER RULING 2026-07-17: probably \"leach\".",
    ("ladder", "Genesis 28:12"):
        "OWNER RULING 2026-07-17: DO NOT CHANGE — Jacob's ladder stays.",
}

HEADER_RE = re.compile(r"^## (.+?) → .*? — (.+)$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--partial", action="store_true",
                    help="allow running before every batch has proposals")
    args = ap.parse_args()

    missing = [b.name for b in sorted(BATCH_DIR.glob("batch_[0-9]*.md"))
               if "_proposals" not in b.name
               and not (BATCH_DIR / f"{b.stem}_proposals.md").exists()]
    if missing and not args.partial:
        raise SystemExit(f"{len(missing)} batches lack proposals "
                         f"(e.g. {missing[:3]}); rerun with --partial or wait")

    nss, ai = [], []
    counts = {"NO-SAFE-SWAP": 0, "KEEP": 0, "REVISE": 0, "other": 0}
    for pf in sorted(BATCH_DIR.glob("batch_*_proposals.md")):
        block, verdict = [], None

        def flush():
            if not block:
                return
            m = HEADER_RE.match(block[0])
            key = (m.group(1).strip().lower(), m.group(2).strip()) if m else None
            entry = list(block)
            entry.insert(1, f"*(from {pf.name})*")
            if key in OWNER_RULINGS:
                entry.insert(2, f"- **{OWNER_RULINGS[key]}**")
            if verdict == "NO-SAFE-SWAP":
                nss.extend(entry + [""])
                counts["NO-SAFE-SWAP"] += 1
            elif verdict in ("KEEP", "REVISE"):
                ai.extend(entry + [""])
                counts[verdict] += 1
            elif verdict:
                nss.extend(entry + [""])
                counts["other"] += 1

        # owner ruling 2026-07-17: owner-facing refs use "Revelation #:#"
        text = pf.read_text(encoding="utf-8").replace(
            "Revelation of John ", "Revelation ")
        for line in text.splitlines():
            if line.startswith("## "):
                flush()
                block, verdict = [line], None
            elif block:
                if line.startswith("- verdict:"):
                    verdict = line.split(":", 1)[1].strip()
                if line.strip():
                    block.append(line)
        flush()

    OUT_NSS.write_text(
        "# Rare-word review: NO-SAFE-SWAP entries (owner ruling needed)\n\n"
        "*Generated by `scripts/28_split_proposals_for_review.py` from the "
        "batch proposal files.* The owner accepts most of these as factual "
        "(the flagged word stays); oddballs carry inline owner rulings.\n\n"
        + "\n".join(nss) + "\n", encoding="utf-8")
    OUT_AI.write_text(
        "# Rare-word review: AI change suggestions (KEEP / REVISE)\n\n"
        "*Generated by `scripts/28_split_proposals_for_review.py` from the "
        "batch proposal files.* Each entry is the agent's suggested "
        "replacement with rationale and full NEW verse text.\n\n"
        + "\n".join(ai) + "\n", encoding="utf-8")
    print(f"split: {counts['NO-SAFE-SWAP']} NO-SAFE-SWAP (+{counts['other']} "
          f"other-verdict) -> {OUT_NSS.name}; {counts['KEEP']} KEEP + "
          f"{counts['REVISE']} REVISE -> {OUT_AI.name}")


if __name__ == "__main__":
    main()
