#!/usr/bin/env python3
"""40_split_round2_proposals.py — split round-2 batch proposals into two
owner-review files (same split as round 1, script 28).

Reads references/rare_word_witness_batches_2/batch_NNNN_proposals_v2.md
(the revised-rules run: every entry carries a mandatory replacement
suggestion + NEW text, and optionally a whitelist-case argument that may
not cite the KJV as authentic; a plain batch_NNNN_proposals.md is used
only if no _v2 exists) and writes, in that same folder:

1. round2_ai_suggestions.md — every REPLACE entry: the agent's suggested
   replacement with rationale and full NEW verse text.
2. round2_whitelist_and_no_safe_swap.md — every WHITELIST and NO-SAFE-SWAP
   entry (owner ruling needed: whitelist the word or accept the flag).
   These entries still include the agent's best-effort suggestion + NEW.

Refuses to run if any batch lacks a proposals file unless --partial is given.
Output files are regenerated wholesale on each run (derived views; the
proposal files remain the preserved source of truth).
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BATCH_DIR = ROOT / "references" / "rare_word_witness_batches_2"
OUT_AI = BATCH_DIR / "round2_ai_suggestions.md"
OUT_WL = BATCH_DIR / "round2_whitelist_and_no_safe_swap.md"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--partial", action="store_true",
                    help="allow running before every batch has proposals")
    args = ap.parse_args()

    batches = [b for b in sorted(BATCH_DIR.glob("batch_[0-9]*.md"))
               if "_proposals" not in b.name]
    proposal_files, missing = [], []
    for b in batches:
        v2 = BATCH_DIR / f"{b.stem}_proposals_v2.md"
        v1 = BATCH_DIR / f"{b.stem}_proposals.md"
        if v2.exists():
            proposal_files.append(v2)
        elif v1.exists():
            proposal_files.append(v1)
        else:
            missing.append(b.name)
    if missing and not args.partial:
        raise SystemExit(f"{len(missing)} batches lack proposals "
                         f"(e.g. {missing[:3]}); rerun with --partial or wait")

    ai, wl = [], []
    counts = {"REPLACE": 0, "WHITELIST": 0, "NO-SAFE-SWAP": 0, "other": 0}
    for pf in proposal_files:
        block, verdict = [], None

        def flush():
            if not block:
                return
            entry = list(block)
            entry.insert(1, f"*(from {pf.name})*")
            if verdict == "REPLACE":
                ai.extend(entry + [""])
                counts["REPLACE"] += 1
            elif verdict in ("WHITELIST", "NO-SAFE-SWAP"):
                wl.extend(entry + [""])
                counts[verdict] += 1
            elif verdict:
                wl.extend(entry + [""])
                counts["other"] += 1

        text = pf.read_text(encoding="utf-8").replace(
            "Revelation of John ", "Revelation ")
        for line in text.splitlines():
            if line.startswith("## "):
                flush()
                block, verdict = [line], None
            elif block:
                if line.startswith("- verdict:"):
                    verdict = line.split(":", 1)[1].strip()
                if line.strip():
                    block.append(line)
        flush()

    OUT_AI.write_text(
        "# Round-2 rare-word review: AI change suggestions (REPLACE)\n\n"
        "*Generated by `scripts/40_split_round2_proposals.py` from the "
        "round-2 batch proposal files (restored-text rare words, "
        "`rare_words_restored.md`).* Each entry is the king-james agent's "
        "suggested replacement with rationale and full NEW verse text.\n\n"
        + "\n".join(ai) + "\n", encoding="utf-8")
    OUT_WL.write_text(
        "# Round-2 rare-word review: WHITELIST candidates & NO-SAFE-SWAP "
        "(owner ruling needed)\n\n"
        "*Generated by `scripts/40_split_round2_proposals.py` from the "
        "round-2 batch proposal files.* WHITELIST entries carry the agent's "
        "compelling reason to protect the word; NO-SAFE-SWAP entries should "
        "change but have no common-KJV candidate.\n\n"
        + "\n".join(wl) + "\n", encoding="utf-8")
    print(f"split: {counts['REPLACE']} REPLACE -> {OUT_AI.name}; "
          f"{counts['WHITELIST']} WHITELIST + {counts['NO-SAFE-SWAP']} "
          f"NO-SAFE-SWAP (+{counts['other']} other) -> {OUT_WL.name}")


if __name__ == "__main__":
    main()
