#!/usr/bin/env python3
"""69_export_scrollmapper.py — export the restored text as a scrollmapper-style DB.

Builds exports/MandelaKJV.db in the exact schema of the bible_databases
sub-repo (formats/sqlite/<translation>.db): `<translation>_books`,
`<translation>_verses`, `translations`. The text is the base KJV with all
APPROVED restorations applied (same composition rule as 17_export_full.py:
approved rows compose, highest id per verse is the complete reading).

Also writes exports/MandelaKJV_schema.md describing the tables.

Idempotent: recreates both output files from scratch each run. Run manually.
"""

import sqlite3
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DB = REPO_ROOT / "db" / "mandela.db"
EXPORT_DIR = REPO_ROOT / "db"
OUT_DB = EXPORT_DIR / "MandelaKJV.db"
OUT_MD = EXPORT_DIR / "MandelaKJV_schema.md"

TRANSLATION = "MandelaKJV"
TITLE = "The Mandela Bible — Memory-Led Restoration of the King James Version"
LICENSE = "Public Domain (derived from the 1769 Blayney KJV text)"


def main() -> None:
    src = sqlite3.connect(SRC_DB)

    resto = {}
    for vid, new in src.execute(
            "SELECT verse_id, proposed_text FROM restorations "
            "WHERE status='approved' AND proposed_text IS NOT NULL ORDER BY id"):
        resto[vid] = new

    OUT_DB.parent.mkdir(exist_ok=True)
    if OUT_DB.exists():
        OUT_DB.unlink()
    out = sqlite3.connect(OUT_DB)
    out.executescript(f"""
        CREATE TABLE {TRANSLATION}_books (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT
        );
        CREATE TABLE {TRANSLATION}_verses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            book_id INTEGER,
            chapter INTEGER,
            verse INTEGER,
            text TEXT,
            FOREIGN KEY (book_id) REFERENCES {TRANSLATION}_books(id)
        );
        CREATE TABLE translations (
            translation TEXT PRIMARY KEY,
            title TEXT,
            license TEXT
        );
    """)
    out.execute("INSERT INTO translations VALUES (?,?,?)",
                (TRANSLATION, TITLE, LICENSE))

    books = src.execute(
        "SELECT id, name FROM books WHERE translation='KJV' ORDER BY id").fetchall()
    for bid, name in books:
        out.execute(f"INSERT INTO {TRANSLATION}_books (id, name) VALUES (?,?)",
                    (bid, name))

    n_verses = n_restored = 0
    for bid, _ in books:
        for vid, ch, vs, text in src.execute(
                "SELECT id, chapter, verse, text FROM verses "
                "WHERE translation='KJV' AND book_id=? ORDER BY chapter, verse",
                (bid,)):
            if vid in resto:
                text = resto[vid]
                n_restored += 1
            out.execute(
                f"INSERT INTO {TRANSLATION}_verses (book_id, chapter, verse, text) "
                "VALUES (?,?,?,?)", (bid, ch, vs, text))
            n_verses += 1
    out.commit()

    md = f"""# MandelaKJV.db — scrollmapper-format export

Generated by `scripts/69_export_scrollmapper.py` on {date.today().isoformat()}.
Format matches the scrollmapper `bible_databases` sub-repo
(`formats/sqlite/<translation>.db`) so the restored text can be offered
upstream as a new translation.

**Content:** the base KJV (1769 Blayney) with {n_restored} owner-approved
restorations applied ({n_verses} verses, {len(books)} books). The restoration
methodology and per-change evidence live in the Mandela Bible project
(`db/mandela.db`, `restorations` table); this file carries text only.

## Tables

### `{TRANSLATION}_books`
| column | type | description |
|---|---|---|
| id | INTEGER PRIMARY KEY AUTOINCREMENT | scrollmapper book id (1 = Genesis … 66 = Revelation) |
| name | TEXT | book name |

### `{TRANSLATION}_verses`
| column | type | description |
|---|---|---|
| id | INTEGER PRIMARY KEY AUTOINCREMENT | sequential verse id in canonical order |
| book_id | INTEGER → {TRANSLATION}_books(id) | book |
| chapter | INTEGER | chapter number |
| verse | INTEGER | verse number |
| text | TEXT | restored verse text |

### `translations`
| column | type | description |
|---|---|---|
| translation | TEXT PRIMARY KEY | `{TRANSLATION}` |
| title | TEXT | full title |
| license | TEXT | license statement |
"""
    OUT_MD.write_text(md, encoding="utf-8")

    print(f"DB: {OUT_DB.relative_to(REPO_ROOT)} "
          f"({len(books)} books, {n_verses} verses, {n_restored} restored)")
    print(f"MD: {OUT_MD.relative_to(REPO_ROOT)}")
    src.close()
    out.close()


if __name__ == "__main__":
    main()
