#!/usr/bin/env python3
"""70_export_project_db.py — export only the project-generated data.

Builds exports/MandelaProject.db: a copy of db/mandela.db without the tables
that are bulk imports of read-only sub-repo corpora (BibleForge word-level
data and lexicons — regenerable from bible_forge_db via
09_convert_bibleforge.py). Everything this project *produced* stays:
memories, restorations, anomalies, scores, word studies, scraped residue,
plus the verses/books/translations reference tables that project rows key on
(verse_id foreign keys would be unreadable without them).

Also writes exports/MandelaProject_schema.md describing every exported table
(schema introspected from the source DB, with row counts).

Idempotent: recreates both output files from scratch each run. Run manually.
"""

import sqlite3
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DB = REPO_ROOT / "db" / "mandela.db"
EXPORT_DIR = REPO_ROOT / "db"
OUT_DB = EXPORT_DIR / "MandelaProject.db"
OUT_MD = EXPORT_DIR / "MandelaProject_schema.md"

# bulk sub-repo imports, excluded from the project export
EXCLUDE = {"bf_words_en", "bf_words_orig", "lexicon_greek", "lexicon_hebrew",
           "sqlite_sequence"}

# one-line purpose per table, for the schema doc
PURPOSE = {
    "anomalies": "Phase-3 detector hits: suspicious tokens/patterns per verse with a suspicion score.",
    "books": "Book id ↔ name per translation (scrollmapper ids, 1=Genesis … 66=Revelation).",
    "corruption_index": "Composite per-verse corruption score with a human-readable component breakdown.",
    "kjvr_highlights": "Phrases highlighted on kingjamesbibleonline.org 'KJV Readers' pages (residue evidence).",
    "kjvr_pages": "Fetched KJV-reader source pages (title, book, URL, size).",
    "kjvr_verses": "Verse texts as they appear on the fetched KJV-reader pages.",
    "memories": "Memory testimony — the project's leading evidence tier (Premise Revision 2026-07-14).",
    "memory_signals": "Supporting signals per memory: alteration artifacts, public memory, advisory witnesses.",
    "punctuation_inventory": "Census of every punctuation character in the base text.",
    "rare_word_witnesses": "Witness readings gathered per rare-word replacement candidate.",
    "restorations": "Proposed/approved/reverted verse changes — the export's source of truth.",
    "translations": "Translations present in the verses table, with title and license.",
    "tsbc_changes": "Imported ThingsSaidBibleChanges change reports (raw JSON preserved).",
    "tsbc_memories": "Remembered readings attached to tsbc_changes rows.",
    "tsbc_residue": "Residue files (images etc.) attached to tsbc_memories rows.",
    "verse_diffs": "Per-verse comparison against each witness translation with similarity score.",
    "verse_stats": "Per-verse length/word metrics and within-book outlier flags.",
    "verses": "Verse texts per translation — the KJV base plus advisory witnesses.",
    "word_counts": "Case-folded word counts per book and bible-wide.",
    "word_era": "Dual-era verdict per word: 1611-English axis and biblical-era-referent axis.",
    "word_forms": "Original-case surface forms per word with counts.",
}


def main() -> None:
    src = sqlite3.connect(SRC_DB)
    tables = [(n, s) for n, s in src.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' ORDER BY name")
        if n not in EXCLUDE]

    OUT_DB.parent.mkdir(exist_ok=True)
    if OUT_DB.exists():
        OUT_DB.unlink()
    out = sqlite3.connect(OUT_DB)

    md = [f"""# MandelaProject.db — project-data export

Generated by `scripts/70_export_project_db.py` on {date.today().isoformat()}.
A copy of `db/mandela.db` containing only data that pertains to the Mandela
Bible project itself. Excluded as regenerable sub-repo imports:
{", ".join(f"`{t}`" for t in sorted(EXCLUDE - {"sqlite_sequence"}))}
(BibleForge word-level KJV and lexicons). The `verses`/`books`/`translations`
reference tables are kept so `verse_id` foreign keys resolve.

## Tables
"""]
    counts = {}
    for name, sql in tables:
        out.execute(sql)
        cols = [r[1] for r in src.execute(f"PRAGMA table_info({name})")]
        ph = ",".join("?" * len(cols))
        collist = ",".join(cols)
        rows = src.execute(f"SELECT {collist} FROM {name}")
        out.executemany(
            f"INSERT INTO {name} ({collist}) VALUES ({ph})", rows)
        counts[name] = out.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]

        md.append(f"### `{name}` — {counts[name]:,} rows")
        md.append(PURPOSE.get(name, ""))
        md.append("\n| column | type | notes |\n|---|---|---|")
        for _, col, ctype, notnull, dflt, pk in src.execute(
                f"PRAGMA table_info({name})"):
            notes = []
            if pk:
                notes.append("primary key")
            if notnull:
                notes.append("not null")
            if dflt is not None:
                notes.append(f"default {dflt}")
            md.append(f"| {col} | {ctype or '(untyped)'} | {', '.join(notes)} |")
        for (fkid, seq, ref_table, col, ref_col, *_rest) in src.execute(
                f"PRAGMA foreign_key_list({name})"):
            md.append(f"\n`{col}` → `{ref_table}({ref_col or 'rowid'})`")
        md.append("")
    out.commit()

    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")
    total = sum(counts.values())
    print(f"DB: {OUT_DB.relative_to(REPO_ROOT)} "
          f"({len(tables)} tables, {total:,} rows)")
    print(f"MD: {OUT_MD.relative_to(REPO_ROOT)}")
    src.close()
    out.close()


if __name__ == "__main__":
    main()
