#!/usr/bin/env python3
"""81_publish_site_editions.py — build the two PUBLISHED editions for the site.

This is the script that produces what mandelabible.com hands out. Both editions
are driven by committed settings files, so the published text can be changed at
any time by editing JSON — no script edits:

  custom/site-original.json → "The Mandela Bible Reconstructed KJV"
                              (restored text in the King James voice)
  custom/site-modern.json   → "Reconstructed KJV in Modern English"
                              (the same, plus the automatic modernization)

It writes markdown + PDF for both into `docs/downloads/` (tracked, served by
GitHub Pages) and rewrites the download buttons on `docs/index.html` between
the EDITIONS:START / EDITIONS:END markers with the current page counts and file
sizes.

Run it after any database change that alters the text — see CLAUDE.md,
"Publishing to the Website".

Usage:
    python3 scripts/81_publish_site_editions.py [--skip-html] [--out-dir DIR]

Idempotent: every run rebuilds all four files from the database and the two
settings files. Nothing is written to db/mandela.db.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from custom_export import (  # noqa: E402
    CUSTOM_DIR, REPO_ROOT, Layer, SettingsError, build_edition, load_settings,
    modernization_layer, report,
)

ORIGINAL_SETTINGS = CUSTOM_DIR / "site-original.json"
MODERN_SETTINGS = CUSTOM_DIR / "site-modern.json"
DOWNLOAD_DIR = REPO_ROOT / "docs" / "downloads"
INDEX_HTML = REPO_ROOT / "docs" / "index.html"
START_MARK = "<!-- EDITIONS:START (generated by scripts/81_publish_site_editions.py) -->"
END_MARK = "<!-- EDITIONS:END -->"


def parse_args(argv):
    out_dir, skip_html = DOWNLOAD_DIR, False
    args = list(argv)
    while args:
        arg = args.pop(0)
        if arg in ("-o", "--out-dir"):
            if not args:
                raise SettingsError("--out-dir needs a directory")
            out_dir = Path(args.pop(0))
        elif arg == "--skip-html":
            skip_html = True
        elif arg in ("-h", "--help"):
            print(__doc__)
            raise SystemExit(0)
        else:
            raise SettingsError(f"unexpected argument: {arg}")
    return out_dir, skip_html


def build_original(out_dir):
    settings = load_settings(ORIGINAL_SETTINGS)
    layer = Layer(f"site settings ({ORIGINAL_SETTINGS.name})",
                  settings.global_replacements, settings.verse_replacements,
                  settings)
    return build_edition([layer], out_dir=out_dir)


def build_modern(out_dir):
    original = load_settings(ORIGINAL_SETTINGS)
    modern = load_settings(MODERN_SETTINGS)
    layers = [
        Layer(f"site settings ({ORIGINAL_SETTINGS.name})",
              original.global_replacements, original.verse_replacements,
              original),
        modernization_layer(modern),
    ]
    return build_edition(layers, out_dir=out_dir)


def _button(result, fmt, primary=False):
    path = result["pdf"] if fmt == "pdf" else result["md"]
    size = path.stat().st_size / 1e6
    detail = (f"PDF, {result['pages']:,} pages" if fmt == "pdf"
              else f"Markdown, {size:.1f} MB")
    cls = "btn primary" if primary else "btn"
    return (f'    <a class="{cls}" href="downloads/{path.name}" download>'
            f'{result["title"]} ({detail})</a>')


def update_index(results) -> bool:
    """Rewrite the download buttons between the markers. True if changed."""
    if not INDEX_HTML.exists():
        raise SettingsError(f"{INDEX_HTML} not found")
    html = INDEX_HTML.read_text(encoding="utf-8")
    if START_MARK not in html or END_MARK not in html:
        raise SettingsError(
            f"{INDEX_HTML.name} has no EDITIONS:START/EDITIONS:END markers — "
            "add them around the download buttons first (see CLAUDE.md, "
            "'Publishing to the Website')")
    buttons = []
    for i, result in enumerate(results):
        buttons.append(_button(result, "pdf", primary=(i == 0)))
        buttons.append(_button(result, "md"))
    head, rest = html.split(START_MARK, 1)
    _old, tail = rest.split(END_MARK, 1)
    block = "\n".join([START_MARK, *buttons, "    "])
    new_html = head + block + END_MARK + tail
    if new_html == html:
        return False
    INDEX_HTML.write_text(new_html, encoding="utf-8")
    return True


def main(argv) -> None:
    out_dir, skip_html = parse_args(argv)
    results = [build_original(out_dir), build_modern(out_dir)]
    for result in results:
        report(result)
    if skip_html:
        print("index.html: skipped (--skip-html)")
        return
    if out_dir != DOWNLOAD_DIR:
        print(f"index.html: skipped (output went to {out_dir}, not "
              f"{DOWNLOAD_DIR.relative_to(REPO_ROOT)})")
        return
    changed = update_index(results)
    print(f"index.html: download buttons "
          f"{'updated' if changed else 'already current'}")


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except SettingsError as exc:
        print(f"ERROR  {exc}")
        raise SystemExit(1)
