#!/usr/bin/env python3
"""84_remaining_words_for_kj.py — owner directive 2026-07-26, step 2.

After scripts/83 whitelisted (A) every token group used more than 88 times
with inflections and (B) every number word archaic or modern, this script
emits what REMAINS — the groups of 88 uses or fewer that are still
unprotected — as a King James agent review file.

The agent's task on that file (see the dispatch prompt / roadmap): flag which
remaining words are **proper nouns, genealogical terms, animals, plants, or
locations**, and recommend whitelisting for those that are **not verbs**.
Verbs are excluded from the recommendation by owner directive — a verb is
ordinary vocabulary and stays reviewable.

Report only: reads references/word_lists/token_list_full.md plus the current
references/word_whitelist.md (to drop anything script 83 already protected)
and writes references/word_lists/kj_whitelist_review_remaining.md. No DB writes.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "references" / "word_lists" / "token_list_full.md"
WHITELIST = ROOT / "references" / "word_whitelist.md"
OUT = ROOT / "references" / "word_lists" / "kj_whitelist_review_remaining.md"
THRESHOLD = 88

ROW = re.compile(r"^\| (\d+) \| (\S+) \| (\d+) \| (.*?) \|(.*)$")
FORM = re.compile(r"(\S+) \(×\d+\)")


def whitelisted():
    wl = WHITELIST.read_text(encoding="utf-8")
    words = {m.lower() for m in re.findall(r"\[([^\]]+)\]\(#", wl)}
    pn = re.search(r"### Proper names and places.*?\n\n(.*?)\n\n## Why", wl, re.S)
    if pn:
        for w in pn.group(1).replace("\n", " ").split(","):
            w = w.strip().lower()
            if w:
                words.add(w)
    return words


def main():
    have = whitelisted()
    rows = []
    for ln in TOKENS.read_text(encoding="utf-8").splitlines():
        m = ROW.match(ln)
        if not m:
            continue
        idx, label, count = int(m.group(1)), m.group(2).lower(), int(m.group(3))
        if count > THRESHOLD:
            continue
        forms = sorted({f.lower() for f in FORM.findall(m.group(4))} | {label})
        if all(f in have for f in forms):
            continue
        refs = m.group(5).strip().strip("|").strip()
        rows.append((idx, label, count, forms, refs))

    L = ["# King James review — whitelist candidates among the remaining words",
         "",
         "*Generated by `scripts/84_remaining_words_for_kj.py` (owner directive "
         "2026-07-26). These are the inflection-grouped token groups of the "
         "restored text that are used **88 times or fewer** and are still "
         "unprotected after scripts/83 whitelisted every group above that "
         "threshold and every number word.*",
         "",
         "**The King James agent's task:** for each word below, judge whether it "
         "is a **proper noun, genealogical term, animal, plant, or location**. "
         "Recommend WHITELIST for those that are **not verbs** (verbs remain "
         "ordinary reviewable vocabulary by owner directive). Everything else "
         "gets no recommendation.",
         "",
         f"**{len(rows)} groups remaining.** Verse references are given where "
         "the token list carried them (groups of 8 uses or fewer).",
         "",
         "| # | word | count | forms | references |",
         "|---|---|---|---|---|"]
    for idx, label, count, forms, refs in rows:
        L.append(f"| {idx} | {label} | {count} | {', '.join(forms)} | {refs} |")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"remaining groups: {len(rows)}")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
