#!/usr/bin/env python3
"""94_merge_token_triage.py — owner request 2026-07-29.

Consolidate the six king-james triage batches written over the remaining token
list (`scripts/93_token_triage_batches.py` built the inputs; the agents wrote
`references/word_reviews/token_triage/batch_N_triage.md`) into one owner-facing
summary:

    references/word_lists/token_triage_summary.md

Same shape as `scripts/85_merge_kj_whitelist_suggestions.py` for the whitelist
review: read-only over the agent artifacts (which are permanent per CLAUDE.md),
group the verdicts, and put the actionable ones on top — REPLACE first, then
WHITELIST, then the KEEP roll-up as a plain list. Each entry keeps the agent's
own suggestion and reason, and names the batch it came from so the full block
is easy to find.

Verdict lines the agents wrote look like:

    ## <group> — <n> uses
    - verdict: KEEP | WHITELIST | REPLACE
    - suggestion: <word or phrase, or "-">
    - reason: <one or two sentences>

The script cross-checks the group labels against the token list and reports any
group that no batch ruled on, so a dropped batch cannot pass unnoticed.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRIAGE_DIR = ROOT / "references" / "word_reviews" / "token_triage"
TOKENS = ROOT / "references" / "word_lists" / "token_list_full.md"
OUT = ROOT / "references" / "word_lists" / "token_triage_summary.md"

HDR = re.compile(r"^## (.+?)\s+—\s+(\d+) uses", re.I)
FIELD = re.compile(
    r"^-\s*(verdict|whitelist|witness|own|suggestion|reason):\s*(.*)$", re.I)
# Round 2 (owner directive 2026-07-29) splits the single `suggestion:` line
# into the three mandatory slots, filled for every verdict.
SLOTS = ["whitelist", "witness", "own", "suggestion"]
ROW = re.compile(r"^\| \d+ \| (\S+) \| (\d+) \|")
ORDER = ["REPLACE", "WHITELIST", "KEEP"]


def parse(path):
    entries, cur = [], None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = HDR.match(line)
        if m:
            cur = {"word": m.group(1).strip().lower(),
                   "count": int(m.group(2)), "batch": path.stem,
                   "verdict": "", "reason": ""}
            cur.update({s: "" for s in SLOTS})
            entries.append(cur)
            continue
        if cur:
            f = FIELD.match(line)
            if f:
                key, val = f.group(1).lower(), f.group(2).strip()
                cur[key] = re.sub(r"^\*+|\*+$", "", val).strip()
    return entries


def main():
    # --tag r2 merges batch_N_r2_triage.md into token_triage_summary_r2.md, so
    # each round of instructions keeps its own artifacts.
    tag = ("_" + sys.argv[sys.argv.index("--tag") + 1].strip("_")
           if "--tag" in sys.argv else "")
    global OUT
    if tag:
        OUT = OUT.with_name(f"token_triage_summary{tag}.md")
    files = sorted(TRIAGE_DIR.glob(f"batch_*{tag}_triage.md"))
    if not tag:      # the untagged run must not swallow tagged rounds
        files = [f for f in files
                 if re.fullmatch(r"batch_\d+_triage", f.stem)]
    if not files:
        sys.exit(f"no batch_*{tag}_triage.md files in "
                 f"{TRIAGE_DIR.relative_to(ROOT)}")

    entries = [e for f in files for e in parse(f)]
    by_verdict = defaultdict(list)
    unknown = []
    for e in entries:
        v = e["verdict"].upper().split()[0] if e["verdict"] else ""
        if v not in ORDER:
            unknown.append(e)
            continue
        by_verdict[v].append(e)

    listed = {m.group(1).lower(): int(m.group(2))
              for m in (ROW.match(l) for l in
                        TOKENS.read_text(encoding="utf-8").splitlines()) if m}
    ruled = {e["word"] for e in entries}
    missing = sorted(set(listed) - ruled)

    total = len(entries)
    lines = [
        "# Token List Triage — King James Pass",
        "",
        f"*Generated by `scripts/94_merge_token_triage.py` from the "
        f"{len(files)} agent batches in "
        "`references/word_reviews/token_triage/` (inputs built by "
        "`scripts/93_token_triage_batches.py`, owner request 2026-07-29).*",
        "",
        "Every inflection group left in `references/word_lists/token_list_full.md` "
        "— the words of the restored text that the whitelist and the "
        "proper-noun exclusions do **not** protect — was ruled on by the "
        "king-james agent: **KEEP** (sound period vocabulary), **WHITELIST** "
        "(protect from all future replacement passes), or **REPLACE** (a real "
        "problem: post-1611 coinage, modern idiom, source-era anachronism, "
        "meaning inversion, or damage left by an earlier pass).",
        "",
        f"**{total} groups ruled** — "
        + ", ".join(f"{len(by_verdict[v])} {v}" for v in ORDER)
        + (f", {len(unknown)} unparsed" if unknown else "") + ".",
        "",
        "Suggestions follow the fixed order of the Rare-Word Review List "
        "Protocol: `[whitelist]` option first, `[witness]` translation second, "
        "then any further option; a suggestion may be a single word or a "
        "phrase. Nothing here is applied — the owner-ruling line under each "
        "entry stays blank for the owner.",
        "",
    ]
    if missing:
        lines += [f"**{len(missing)} groups in the token list were not ruled "
                  f"on**: " + ", ".join(missing), ""]

    for verdict in ORDER:
        rows = sorted(by_verdict[verdict], key=lambda e: (-e["count"], e["word"]))
        lines += [f"## {verdict} ({len(rows)})", ""]
        if verdict == "KEEP" and not any(e["whitelist"] for e in rows):
            # round-1 shape: KEEP entries carried no suggestions
            lines += ["Sound Early Modern English naming things of the "
                      "biblical world; no action.", "",
                      ", ".join(f"{e['word']} ({e['count']})" for e in rows),
                      ""]
            continue
        for e in rows:
            lines.append(f"### {e['word']} — {e['count']} uses")
            for slot in SLOTS:
                if e[slot] and e[slot] != "-":
                    lines.append(f"- {slot}: {e[slot]}")
            lines.append(f"- reason: {e['reason']}")
            lines.append(f"- source: `{e['batch']}.md`")
            lines.append("- **OWNER RULING:**")
            lines.append("")

    if unknown:
        lines += ["## Unparsed entries", ""]
        lines += [f"- {e['word']} ({e['batch']}): {e['verdict']!r}"
                  for e in unknown] + [""]

    # Owner-reviewed files are re-read, never regenerated (CLAUDE.md): once a
    # ruling line has been filled in, a rerun must not blank it.
    if OUT.exists() and "--force" not in sys.argv:
        filled = [l for l in OUT.read_text(encoding="utf-8").splitlines()
                  if l.startswith("- **OWNER RULING") and l.rstrip() not in
                  ("- **OWNER RULING:**", "- **OWNER RULING:** ")]
        if filled:
            sys.exit(f"refusing to overwrite {OUT.name}: it carries "
                     f"{len(filled)} filled-in owner ruling(s). Re-run with "
                     "--force only if you mean to discard them.")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {total} groups — "
          + ", ".join(f"{v} {len(by_verdict[v])}" for v in ORDER))
    if missing:
        print(f"WARNING: {len(missing)} token-list groups unruled: "
              + ", ".join(missing[:20]))
    if unknown:
        print(f"WARNING: {len(unknown)} entries had an unrecognized verdict")


if __name__ == "__main__":
    main()
