#!/usr/bin/env python3
"""98_kjv_word_index_not_blacklisted.py — list the KJV Bible Word Index
entries (references/eya-new-words-list/, script 97) whose words are NOT on
references/word_blacklist.md (owner request 2026-10-04).

An index entry can name several forms ("Abase / Abased / Abasing") in a
shorthand ("Alien/s", "Brake/s / Brakest", "Bank (for money)"). Each entry
is expanded into its forms:
  - parenthetical notes are dropped;
  - parts split on "/"; a part of 1–3 lowercase letters ("s", "es", "d")
    is a suffix appended to the preceding full form (a doubled "e" is merged), otherwise it is a form
    of its own (phrases stay phrases).
Each form is matched case-insensitively against the blacklist headwords (the
text before " → " in each `#### <a name=...>` heading).

Output: references/eya-new-words-list/not_on_blacklist.md with
  1. entries with NO form on the blacklist, and
  2. entries with SOME forms on the blacklist (the remaining forms listed).
Read-only on every input; overwrite guard refuses a version with fewer
entries than the existing file.
"""
import csv
import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "references" / "eya-new-words-list" / "kjv_word_index.tsv"
BLACKLIST = ROOT / "references" / "word_blacklist.md"
OUT = ROOT / "references" / "eya-new-words-list" / "not_on_blacklist.md"


def blacklist_headwords():
    heads = set()
    for line in BLACKLIST.read_text(encoding="utf-8").splitlines():
        m = re.match(r"#### <a name=\"[^\"]*\"></a>(.*?) → ", line)
        if m:
            heads.add(m.group(1).strip().lower())
    return heads


def expand(entry):
    text = re.sub(r"\([^)]*\)", "", entry)
    forms = []
    for part in (p.strip() for p in text.split("/")):
        if not part:
            continue
        if re.fullmatch(r"[a-z]{1,3}", part) and forms:
            base = forms[-1]
            if base.endswith("e") and part.startswith("e"):
                base = base[:-1]  # "Cheese/es" → cheeses, not cheesees
            forms.append(base + part)
        else:
            forms.append(" ".join(part.split()))
    return list(OrderedDict.fromkeys(forms))


def main():
    heads = blacklist_headwords()
    entries = OrderedDict()  # entry -> [times, verse count]
    with TSV.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            e = entries.setdefault(row["word"], [row["times_in_kjv"], 0])
            e[1] += 1

    clear, partial = [], []
    for entry, (times, verses) in entries.items():
        forms = expand(entry)
        listed = [w for w in forms if w.lower() in heads]
        free = [w for w in forms if w.lower() not in heads]
        if not listed:
            clear.append((entry, times, verses))
        elif free:
            partial.append((entry, times, free, listed))

    md = [
        "# KJV Word Index — words not on the blacklist",
        "",
        "Generated by `scripts/98_kjv_word_index_not_blacklisted.py` from "
        "`kjv_word_index.tsv` and `references/word_blacklist.md` "
        f"({len(heads)} headwords). Each index entry is expanded into its "
        "forms (`Alien/s` → alien, aliens; parenthetical notes dropped) and "
        "every form is matched case-insensitively against the blacklist "
        "headwords.",
        "",
        f"**{len(entries)} index entries: {len(clear)} with no form on the "
        f"blacklist, {len(partial)} with only some forms on it, "
        f"{len(entries) - len(clear) - len(partial)} fully blacklisted.**",
        "",
        f"## 1. No form on the blacklist ({len(clear)})",
        "",
        "| Index entry | Times in KJV (site) | Example verses |",
        "|---|---|---|",
    ]
    md += [f"| {e} | {t} | {v} |" for e, t, v in clear]
    md += [
        "",
        f"## 2. Some forms on the blacklist ({len(partial)})",
        "",
        "| Index entry | Times in KJV (site) | Not on blacklist | On blacklist |",
        "|---|---|---|---|",
    ]
    md += [f"| {e} | {t} | {', '.join(f)} | {', '.join(l)} |"
           for e, t, f, l in partial]
    text = "\n".join(md) + "\n"

    if OUT.exists():
        old = OUT.read_text(encoding="utf-8")
        if old == text:
            print(f"{OUT.relative_to(ROOT)}: already current")
            return
        old_rows = len(re.findall(r"^\| (?!Index entry|---)", old, re.M))
        if len(clear) + len(partial) < old_rows:
            print(f"REFUSED: {OUT.relative_to(ROOT)} has {old_rows} rows; "
                  f"new version has {len(clear) + len(partial)}.")
            return
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(clear)} clear, {len(partial)} partial, "
          f"{len(entries) - len(clear) - len(partial)} fully blacklisted")


if __name__ == "__main__":
    main()
