#!/usr/bin/env python3
"""99_kjv_word_index_on_whitelist.py — list the KJV Bible Word Index entries
(references/eya-new-words-list/, script 97) whose words ARE on
references/word_whitelist.md (owner request 2026-10-04).

Each index entry is expanded into its forms with the same rules as script 98
(`expand()` is imported from it, so both lists split entries identically).
Each form is matched case-insensitively against both whitelist sections:
  - "Reviewed no-safe-swap words" — the `[word](#anchor),` index lines;
  - "Proper names and places"     — the bare `word,` lines.

Output: references/eya-new-words-list/on_whitelist.md with
  1. entries with EVERY form on the whitelist, and
  2. entries with SOME forms on it (whitelisted and other forms listed).
Read-only on every input; overwrite guard refuses a version with fewer
entries than the existing file.
"""
import csv
import importlib
import re
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = ROOT / "references" / "eya-new-words-list" / "kjv_word_index.tsv"
WHITELIST = ROOT / "references" / "word_whitelist.md"
OUT = ROOT / "references" / "eya-new-words-list" / "on_whitelist.md"

sys.path.insert(0, str(ROOT / "scripts"))
expand = importlib.import_module("98_kjv_word_index_not_blacklisted").expand

NAMES_HDR = re.compile(r"^### Proper names and places \(\d+\)$")


def whitelist_sections():
    reviewed, names, section = set(), set(), None
    for line in WHITELIST.read_text(encoding="utf-8").splitlines():
        if line.startswith("### Reviewed no-safe-swap words"):
            section = "reviewed"
        elif NAMES_HDR.match(line):
            section = "names"
        elif line.startswith("#"):
            section = None  # description blocks follow the two index lists
        elif section == "reviewed":
            m = re.match(r"^\[([^\]]+)\]\(#", line)
            if m:
                reviewed.add(m.group(1).lower())
        elif section == "names":
            m = re.fullmatch(r"([^\s,\[]+),?", line.strip())
            if m:
                names.add(m.group(1).lower())
    return reviewed, names


def main():
    reviewed, names = whitelist_sections()
    entries = OrderedDict()  # entry -> [times, verse count]
    with TSV.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            e = entries.setdefault(row["word"], [row["times_in_kjv"], 0])
            e[1] += 1

    def tag(w):
        lw = w.lower()
        return "name" if lw in names else "reviewed" if lw in reviewed else None

    full, partial = [], []
    for entry, (times, verses) in entries.items():
        forms = expand(entry)
        listed = [(w, tag(w)) for w in forms if tag(w)]
        other = [w for w in forms if not tag(w)]
        if not listed:
            continue
        cell = ", ".join(f"{w} ({t})" for w, t in listed)
        if other:
            partial.append((entry, times, cell, ", ".join(other)))
        else:
            full.append((entry, times, verses, cell))

    md = [
        "# KJV Word Index — words on the whitelist",
        "",
        "Generated by `scripts/99_kjv_word_index_on_whitelist.py` from "
        "`kjv_word_index.tsv` and `references/word_whitelist.md` "
        f"({len(reviewed)} reviewed words, {len(names)} proper names). Each "
        "index entry is expanded into its forms the same way as "
        "`not_on_blacklist.md` (`Alien/s` → alien, aliens; parenthetical "
        "notes dropped) and every form is matched case-insensitively. "
        "*(reviewed)* = owner-reviewed no-safe-swap word; *(name)* = proper "
        "names and places.",
        "",
        f"**{len(entries)} index entries: {len(full)} with every form on the "
        f"whitelist, {len(partial)} with only some forms on it, "
        f"{len(entries) - len(full) - len(partial)} with none.**",
        "",
        f"## 1. Every form on the whitelist ({len(full)})",
        "",
        "| Index entry | Times in KJV (site) | Example verses | Whitelisted as |",
        "|---|---|---|---|",
    ]
    md += [f"| {e} | {t} | {v} | {c} |" for e, t, v, c in full]
    md += [
        "",
        f"## 2. Some forms on the whitelist ({len(partial)})",
        "",
        "| Index entry | Times in KJV (site) | On whitelist | Not on whitelist |",
        "|---|---|---|---|",
    ]
    md += [f"| {e} | {t} | {c} | {o} |" for e, t, c, o in partial]
    text = "\n".join(md) + "\n"

    if OUT.exists():
        old = OUT.read_text(encoding="utf-8")
        if old == text:
            print(f"{OUT.relative_to(ROOT)}: already current")
            return
        old_rows = len(re.findall(r"^\| (?!Index entry|---)", old, re.M))
        if len(full) + len(partial) < old_rows:
            print(f"REFUSED: {OUT.relative_to(ROOT)} has {old_rows} rows; "
                  f"new version has {len(full) + len(partial)}.")
            return
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(full)} full, {len(partial)} partial, "
          f"{len(entries) - len(full) - len(partial)} none")


if __name__ == "__main__":
    main()
